proxy:
  secretToken: "1234123412341234123412341234123412341234123412341234123412341234"
  https:
    enabled: false
  service:
    type: LoadBalancer
  https:
    enabled: true
    hosts:
      - "129.114.109.246.nip.io"
    letsencrypt:
      contactEmail: "grunwald@colorado.edu"

hub:
  shutdownOnLogout: True  

singleuser:
  defaultUrl: "/lab"
  storage:
    capacity: 0.5Gi
    dynamic:
      storageClass: nfs
    extraVolumes:
      - name: jupyterhub-shared
        persistentVolumeClaim:
          claimName: jupyterhub-shared-volume
    extraVolumeMounts:
      - name: jupyterhub-shared
        mountPath: /home/jovyan/shared/example
