debug:
  enabled: true

proxy:
  secretToken: "1234123412341234123412341234123412341234123412341234123412341234"
  service:
    type: LoadBalancer
  https:
    enabled: true
    hosts:
      - "129.114.109.246.nip.io"
    letsencrypt:
      contactEmail: "grunwald@colorado.edu"


hub:
  shutdownOnLogout: True

singleuser:
  defaultUrl: "/lab"
